services:
  mongodb:
    image: mongo:latest
    container_name: miniface_db
    ports:
      - 27018:27017  # Cổng 27018 
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: